export const CHANGE_BANNERS = 'recommend/CHANGE_BANNERS'
export const CHANGE_HOT_RECOMMENDS = 'recommend/CHANGE_HOT_RECOMMENDS'
export const CHANGE_NEW_ALBUMS = 'recommend/CHANGE_NEW_ALBUMS'

export const CHANGE_RISING_RANKING = 'recommend/CHANGE_RISING_RANKING'
export const CHANGE_NEW_RANKING = 'recommend/CHANGE_NEW_RANKING'
export const CHANGE_ORIGIN_RANKING = 'recommend/CHANGE_ORIGIN_RANKING'

export const CHANGE_ENTER_SINGERS = 'recommend/CHANGE_ENTER_SINGERS'